# scenario: low-latency
apiVersion: fournos.dev/v1
kind: FournosJob
metadata:
  generateName: rhaiis-g4-31b-it-qat-w4a16-ct-ll-
spec:
  owner: nmiriyal
  displayName: rhaiis-g4-31b-it-qat-w4a16-ct-ll
  pipeline: forge-full
  exclusive: false
  cluster: zeus
  priority: manual
  hardware:
    gpuType: h200
    gpuCount: 1
  secretRefs:
  - psap-forge-dashboard-s3
  - psap-forge-notifications
  executionEngine:
    forge:
      project: rhaiis
      args:
        - nvidia
        - vllm
        - zeus
        - profile4
        - profile6
      configOverrides:
        tests.rhaiis.run_benchmark: true
        tests.rhaiis.slack_user: "U08RXCZRRNF"
        tests.rhaiis.slack_notify_always: true
        caliper.postprocess.csv_dashboard.enabled: true
        rhaiis.profiler.enabled: true
        rhaiis.agent_analysis.enabled: false
        rhaiis.deploy.image_pull_secrets: ["npalaska-image-pull"]

        benchmarks.guidellm.fs_group: 0
        tests.rhaiis.warmup: true

        rhaiis.engines.vllm.images.nvidia: "vllm/vllm-openai:v0.29.0"
        tests.rhaiis.version: "vLLM-0.29.0-recipe-latency-oriented"

        tests.rhaiis.model_key: custom
        models.custom.hf_model_id: "google/gemma-4-31B-it-qat-w4a16-ct"
        rhaiis.engines.vllm.args.tensor-parallel-size: 1
        rhaiis.engines.vllm.args.language-model-only: true
        rhaiis.engines.vllm.args.enable-prefix-caching: true

        tests.rhaiis.workload_keys: ["profile4","profile6"]
        workloads.profile4.rates: [1,2,4,8,16,32,64,128,256]
        workloads.profile4.max_seconds: 450
        workloads.profile4.rampup: 0
        workloads.profile6.rates: [1,2,4,8,16,32,64,128,256]
        workloads.profile6.max_seconds: 450
        workloads.profile6.rampup: 0
  env:
    PULL_PULL_SHA: "forge-rhaiis-v0.0.6"
