# scenario: low-latency
apiVersion: fournos.dev/v1
kind: FournosJob
metadata:
  generateName: rhaiis-ntr-35-ltn-30b-a3b-nvfp4-ll-
spec:
  owner: nmiriyal
  displayName: rhaiis-ntr-35-ltn-30b-a3b-nvfp4-ll
  pipeline: forge-full
  exclusive: false
  cluster: zeus
  priority: manual
  hardware:
    gpuType: h200
    gpuCount: 1
  secretRefs:
  - psap-forge-dashboard-s3
  - psap-forge-notifications
  executionEngine:
    forge:
      project: rhaiis
      args:
        - nvidia
        - vllm
        - zeus
        - profile4
        - profile6
      configOverrides:
        tests.rhaiis.run_benchmark: true
        tests.rhaiis.slack_user: "U08RXCZRRNF"
        tests.rhaiis.slack_notify_always: true
        caliper.postprocess.csv_dashboard.enabled: true
        rhaiis.profiler.enabled: true
        rhaiis.agent_analysis.enabled: false
        rhaiis.deploy.image_pull_secrets: ["npalaska-image-pull"]

        benchmarks.guidellm.fs_group: 0
        tests.rhaiis.warmup: true

        rhaiis.engines.vllm.images.nvidia: "vllm/vllm-openai:v0.29.0"
        tests.rhaiis.version: "vLLM-0.29.0-recipe-latency-oriented"

        tests.rhaiis.model_key: custom
        models.custom.hf_model_id: "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-NVFP4"
        rhaiis.engines.vllm.args.mamba-backend: "flashinfer"
        rhaiis.engines.vllm.args.mamba-cache-mode: "align"
        rhaiis.engines.vllm.args.enable-prefix-caching: true
        rhaiis.engines.vllm.args.kv-cache-dtype: "fp8"
        rhaiis.engines.vllm.args.tensor-parallel-size: 1
        rhaiis.engines.vllm.args.quantization: "modelopt_fp4"
        rhaiis.engines.vllm.args.moe-backend: "humming"
        rhaiis.engines.vllm.args.linear-backend: "humming"
        rhaiis.engines.vllm.args.mamba-ssu-algorithm: "horizontal"
        rhaiis.engines.vllm.args.async-scheduling: true
        rhaiis.engines.vllm.args.max-num-seqs: 256
        rhaiis.engines.vllm.args.max-num-batched-tokens: 32768

        tests.rhaiis.workload_keys: ["profile4"]
        workloads.profile4.rates: [1,2,4,8,16,32,64,128,256]
        workloads.profile4.max_seconds: 450
        workloads.profile4.rampup: 0
  env:
    PULL_PULL_SHA: "forge-rhaiis-v0.0.6"
