# scenario: low-latency
apiVersion: fournos.dev/v1
kind: FournosJob
metadata:
  generateName: rhaiis-q38-27b-ll-
spec:
  owner: nmiriyal
  displayName: rhaiis-q38-27b-ll
  pipeline: forge-full
  exclusive: false
  cluster: zeus
  priority: manual
  hardware:
    gpuType: h200
    gpuCount: 1
  secretRefs:
  - psap-forge-dashboard-s3
  - psap-forge-notifications
  executionEngine:
    forge:
      project: rhaiis
      args:
        - nvidia
        - vllm
        - zeus
      configOverrides:
        tests.rhaiis.run_benchmark: true
        tests.rhaiis.slack_user: "U08RXCZRRNF"
        tests.rhaiis.slack_notify_always: true
        caliper.postprocess.csv_dashboard.enabled: true
        rhaiis.profiler.enabled: true
        rhaiis.agent_analysis.enabled: false
        rhaiis.deploy.image_pull_secrets: ["npalaska-image-pull"]

        benchmarks.guidellm.fs_group: 0
        tests.rhaiis.warmup: true

        rhaiis.engines.vllm.images.nvidia: "vllm/vllm-openai:v0.29.0"
        tests.rhaiis.version: "vLLM-0.29.0-recipe-delete5"

        tests.rhaiis.model_key: custom
        models.custom.hf_model_id: "Qwen/Qwen3.8-27B"
        rhaiis.engines.vllm.args.tensor-parallel-size: 1
        rhaiis.engines.vllm.args.language-model-only: true
        rhaiis.engines.vllm.args.enable-prefix-caching: true

        tests.rhaiis.workload_keys: ["custom"]
        workloads.custom.rates: [1]
        workloads.custom.max_seconds: 300
        workloads.custom.rampup: 0
        workloads.custom.data: "prompt_tokens=128,output_tokens=128,turns=10,prefix_count=512,prefix_tokens=10000"
  env:
    PULL_PULL_SHA: "b115f4af2e0249457b6590edb9126a6b2bd1d36e"
